### PR TITLE
DiscordMail no longer removes bot collection guilds

### PR DESCRIPTION
**Pull request by 7coil**
This is because rethonk died on me once.

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
But do you need to remove it?
I mean, it still has valuable IDs

**Comment by jakeoid** [comment]
I concur

**Comment by 7coil** [comment]
Well the /API/collection URL no longer works - I'll back up the contents of the database and add it as a file

**Comment by 7coil** [comment]
Well you're going to have to delete it - I've already deleted the data. :mmLol:

Say thanks to the Data Protection Act

**Comment by AlexFlipnote** [comment]
If you have any problems, DM me instead of trying to mmLol it here on Github.

**Pull request closed without merging**
